### ISSUE TITLE
where is it Get linear-model-esque interpretations from non-linear models.?

### ISSUE THREAD

**Issue by Sandy4321** [jesse-toftum/cash_ml#10]
Get linear-model-esque interpretations from non-linear models. More information available in the documentation: https://cash-ml.readthedocs.io

may you help find location and example , pls

**Comment by jesse-toftum** [comment]
I'm not sure what it is that you mean by this

**Comment by Sandy4321** [comment]
your wrote:Feature Responses
Get linear-model-esque interpretations from non-linear models. More information available in the documentation: https://cash-ml.readthedocs.io

so where to read details about this
since link just sends to main page
Welcome to cash_ml’s documentation!
![image](https://user-images.githubusercontent.com/11426119/50840319-34667a80-1330-11e9-9cb4-378044dae1a3.png)

**Comment by Sandy4321** [comment]
and search for linear-model-esque
giving nothing 
![image](https://user-images.githubusercontent.com/11426119/50840385-68da3680-1330-11e9-8086-08bdc7d319e2.png)

**Comment by jesse-toftum** [comment]
That's a good point, I'm going to change the link to redirect to https://cash-ml.readthedocs.io/en/latest/feature_responses.html for clarity.

**Comment by Sandy4321** [comment]
do you mean : you will add more material to  https://cash-ml.readthedocs.io/en/latest/feature_responses.html 
about linear-model-esque interpretations from non-linear models

**Comment by above-c-level** [comment]
That is not what I meant. As it stands, this project is of much lower priority than school, as it's more of a hobby.
