### ISSUE TITLE
is "Using machine learning for analytics" works only for random forest

### ISSUE THREAD

**Issue by Sandy4321** [jesse-toftum/cash_ml#11]
this link uses only random forest?
https://cash-ml.readthedocs.io/en/latest/analytics.html?highlight=esque

what can be done for xgboost or black box algorithm?

**Comment by jesse-toftum** [comment]
You are correct. I may possibly get back to this later but mostly I'm focused on making the code workable and maintainable for the future.

> The only types of models that support introspection like this currently are tree-based models (DecisionTree, RandomForest, XGBoost/GradientBoosted trees, etc.), and regression models (LinearRegression, LogisticRegression, Ridge, etc.).

**Comment by Sandy4321** [comment]
just to make sure , can I use it today for Catboost or  XGBoost

**Comment by above-c-level** [comment]
I haven't tested it, but I believe you should be able to use Catboost and XGBoost.
