### ISSUE TITLE
May you clarify, is it new code for update for https://github.com/ClimbsRocks/auto_ml/issues/416#issuecomment-436221535

### ISSUE THREAD

**Issue by Sandy4321** [jesse-toftum/cash_ml#8]
you wrote
https://github.com/ClimbsRocks/auto_ml/issues/416#issuecomment-436221535
Hey there! It appears that this repository is no longer being actively maintained. However, I still think it's a great idea, so I've started working on my own version of it, which you can find here.

May you clarify, is it new code for update for https://github.com/ClimbsRocks/auto_ml/issues/416#issuecomment-436221535

**Comment by jesse-toftum** [comment]
It is indeed a (more) updated version of auto_ml, and I have removed `calc_feature_importance=True` in utils_models.py

**Comment by Sandy4321** [comment]
your wrote It is indeed a (more) updated version of auto_ml
may you share link to this?
